[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "mimictest"
version = "0.1"
dependencies = [
    "diffusers",
    "einops",
    "accelerate",
    "moviepy",
    "wandb",
    "tqdm",
    "stable-baselines3",
]

[project.optional-dependencies]
florence = [
    "transformers",
    "timm",
    "flash-attn",
]
robomimic = [
    "robomimic",
    "robosuite",
]
pusht = [
    "gym-pusht",
]


[tool.setuptools]
packages = ["mimictest"]